---
- name: Install Velero CLI
  become_user: root
  become_method: sudo
  become: yes
  shell: curl -fsSL -o velero.tar.gz https://github.com/vmware-tanzu/velero/releases/download/v1.6.2/velero-v1.6.2-linux-amd64.tar.gz
- name: Install Velero CLI
  become_user: root
  become_method: sudo
  become: yes
  shell: tar -xvf velero.tar.gz
- name: Install Velero CLI
  become_user: root
  become_method: sudo
  become: yes
  shell: mv velero-v1.6.2-linux-amd64/velero /usr/local/bin


- name: Install Velero for Azure
  become_user: hl
  become_method: sudo
  become: yes
  shell: velero install --provider gcp --plugins velero/velero-plugin-for-gcp:v1.2.0 --bucket playground2-velero --secret-file={{vault_secret}} 