---
- name: version
  command: velero version --client-only
  register: velero_installed_version
  changed_when: false
  failed_when: false

- block:
    - name: download
      get_url:
        url: "{{ velero_url }}"
        dest: /tmp
        checksum: "{{ velero_checksum }}"

    - block:
        - name: unarchive
          unarchive:
            src: "/tmp/{{ velero_pkg_ext }}"
            dest: /usr/local/bin
            remote_src: true
        - name: executable bin for every user
          copy:
            src: "/usr/local/bin{{ velero_pkg_bin }}"
            dest: "{{ velero_bin }}"
            remote_src: true
            owner: root
            group: root
            mode: '0755'
        - name: write creds.json
          copy:
            content: "{{ vault_secret }}"
            dest: "{{ config_dir }}/creds.json"
            mode: '0644'
          vars:
            vault_secret: "{{ lookup('community.hashi_vault.hashi_vault',
                             'secret={{ jenkins_secret }}
                              auth_method=approle
                              role_id={{ role_id }}
                              secret_id={{ secret_id }}
                              url={{ vault_server }}
                             ') }}"
        - name: Install velero
          shell: velero install --provider gcp --plugins velero/velero-plugin-for-gcp:v1.2.0 --bucket playground2-velero --secret-file "{{ config_dir }}/creds.json"
      become: true
  when: >
    velero_installed_version.stdout is not defined
    or velero_version not in velero_installed_version.stdout
